### ISSUE TITLE
IllegalStateException in nav-component-2-tabs

### ISSUE THREAD

**Issue by vellrya** [romychab/android-tutorials#1]
Здравствуйте, небольшое уточнение для примера nav-component-2-tabs.
Темная тема (если установлена по умолчанию на устройстве) наследуется от Theme.MaterialComponents.DayNight.**DarkActionBar**, поэтому при попытке добавить кастомный тулбар приложение падает.

Решается заменой на Theme.MaterialComponents.DayNight.NoActionBar, но я бы на вашем месте вообще удалил values-night, а в основной теме использовал бы наследование от Theme.MaterialComponents.**Light**.NoActionBar, потому что в темном варианте текст не читаем.
![image](https://user-images.githubusercontent.com/13716114/168494104-e6b5bbdf-5bb1-41ed-baff-6521cddddb92.png)

Наверное, есть более элегантное решение, но мне всегда было лень разбираться)

**Comment by romychab** [comment]
Спасибо! :) Все верно, в основной теме установлен NoActionBar, а в ночной - нет. Исправил и перезалил исходники.
